#ifndef RTCCOMPONENT_GLOBAL_H
#define RTCCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RTCCOMPONENT_LIBRARY)
#  define RTCCOMPONENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RTCCOMPONENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RTCCOMPONENT_GLOBAL_H
